[bullsys]
[defines]
NAME="bullsys"
VERSION=""

[profile.default]
compiler="gcc"
flags="-Wall -Wextra -stc=c99"
source="src/"
include="lib/"
output="build/"

[profile.release]
flags="-Wall -Wextra -stc=c99 -O2 -DNDEBUG"
output="build/release/"

; [run]
; cmd="./build/bullsys"

[clean]
cmd="rm -rf $(output)"
